---
abstract: ~
author:
  - 'Kieren Diment <zarquon@cpan.org>'
  - 'Kieren Diment <zarquon@cpan.org>'
build_requires:
  Catalyst::Runtime: 0
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.42
  Test::Command: 0
  Test::More: 0.88
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-AuthDBIC
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Authentication::Credential::HTTP: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Devel: 0
  Catalyst::Model::DBIC::Schema: 0.40
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  DBIx::Class::EncodedColumn: 0
  DBIx::Class::Schema::Loader: 0.05003
  PPI: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Helper-AuthDBIC/trunk/
version: 0.17
