abstract: ~
author: Kieren Diment <zarquon@cpan.org>
build_requires: 
  Catalyst::Runtime: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Helper-AuthDBIC
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authentication::Store::DBIC: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  DBIx::Class::DigestColumns: 0
  DBIx::Class::Schema::Loader: 0
  Digest::SHA1: 0
  PPI: 0
version: 0.04
